name: CI/CD - Build & Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHCR_TOKEN }}


      # Build & push backend
      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/mohammedelghanam/remot-server-backend:latest